<?php

use Illuminate\Database\Seeder;
use App\Data\Entities\Country;

class CountryTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Country::insert(['name' => 'Afghanistan', 'long_name' => 'Islamic Republic of Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'numcode' => '4', 'calling_code' => '93', 'nationality' => 'Afghan']);
        Country::insert(['name' => 'Aland Islands', 'long_name' => '&Aring;land Islands', 'iso2' => 'AX', 'iso3' => 'ALA', 'numcode' => '248', 'calling_code' => '358', 'nationality' => 'Aland Island']);
        Country::insert(['name' => 'Albania', 'long_name' => 'Republic of Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'numcode' => '8', 'calling_code' => '355', 'nationality' => 'Albanian']);
        Country::insert(['name' => 'Algeria', 'long_name' => 'People\'s Democratic Republic of Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'numcode' => '12', 'calling_code' => '213', 'nationality' => 'Algerian']);
        Country::insert(['name' => 'American Samoa', 'long_name' => 'American Samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'numcode' => '16', 'calling_code' => '1+684', 'nationality' => 'American Sam']);
        Country::insert(['name' => 'Andorra', 'long_name' => 'Principality of Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'numcode' => '20', 'calling_code' => '376', 'nationality' => 'Andorran']);
        Country::insert(['name' => 'Angola', 'long_name' => 'Republic of Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'numcode' => '24', 'calling_code' => '244', 'nationality' => 'Angolan']);
        Country::insert(['name' => 'Anguilla', 'long_name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'numcode' => '660', 'calling_code' => '1+264', 'nationality' => 'Anguillan']);
        Country::insert(['name' => 'Antarctica', 'long_name' => 'Antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'numcode' => '10', 'calling_code' => '672', 'nationality' => 'Antartican']);
        Country::insert(['name' => 'Antigua and Barbuda', 'long_name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'numcode' => '28', 'calling_code' => '1+268', 'nationality' => 'Antiguan']);
        Country::insert(['name' => 'Argentina', 'long_name' => 'Argentine Republic', 'iso2' => 'AR', 'iso3' => 'ARG', 'numcode' => '32', 'calling_code' => '54', 'nationality' => 'Argentine']);
        Country::insert(['name' => 'Armenia', 'long_name' => 'Republic of Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'numcode' => '51', 'calling_code' => '374', 'nationality' => 'Armenian']);
        Country::insert(['name' => 'Aruba', 'long_name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'numcode' => '533', 'calling_code' => '297', 'nationality' => 'Aruban']);
        Country::insert(['name' => 'Australia', 'long_name' => 'Commonwealth of Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'numcode' => '36', 'calling_code' => '61', 'nationality' => 'Australian']);
        Country::insert(['name' => 'Austria', 'long_name' => 'Republic of Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'numcode' => '40', 'calling_code' => '43', 'nationality' => 'Austrian']);
        Country::insert(['name' => 'Azerbaijan', 'long_name' => 'Republic of Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'numcode' => '31', 'calling_code' => '994', 'nationality' => 'Azerbaijani']);
        Country::insert(['name' => 'Bahamas', 'long_name' => 'Commonwealth of The Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'numcode' => '44', 'calling_code' => '1+242', 'nationality' => 'Bahamian']);
        Country::insert(['name' => 'Bahrain', 'long_name' => 'Kingdom of Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'numcode' => '48', 'calling_code' => '973', 'nationality' => 'Bahraini']);
        Country::insert(['name' => 'Bangladesh', 'long_name' => 'People\'s Republic of Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'numcode' => '50', 'calling_code' => '880', 'nationality' => 'Bangladeshi']);
        Country::insert(['name' => 'Barbados', 'long_name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'numcode' => '52', 'calling_code' => '1+246', 'nationality' => 'Barbadian']);
        Country::insert(['name' => 'Belarus', 'long_name' => 'Republic of Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'numcode' => '112', 'calling_code' => '375', 'nationality' => 'Belarusian']);
        Country::insert(['name' => 'Belgium', 'long_name' => 'Kingdom of Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'numcode' => '56', 'calling_code' => '32', 'nationality' => 'Belgian']);
        Country::insert(['name' => 'Belize', 'long_name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'numcode' => '84', 'calling_code' => '501', 'nationality' => 'Belizean']);
        Country::insert(['name' => 'Benin', 'long_name' => 'Republic of Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'numcode' => '204', 'calling_code' => '229', 'nationality' => 'Beninese']);
        Country::insert(['name' => 'Bermuda', 'long_name' => 'Bermuda Islands', 'iso2' => 'BM', 'iso3' => 'BMU', 'numcode' => '60', 'calling_code' => '1+441', 'nationality' => 'Bermudian']);
        Country::insert(['name' => 'Bhutan', 'long_name' => 'Kingdom of Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'numcode' => '64', 'calling_code' => '975', 'nationality' => 'Bhutanese']);
        Country::insert(['name' => 'Bolivia', 'long_name' => 'Plurinational State of Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'numcode' => '68', 'calling_code' => '591', 'nationality' => 'Bolivian']);
        Country::insert(['name' => 'Bonaire, Sint Eustatius and Saba', 'long_name' => 'Bonaire, Sint Eustatius and Saba', 'iso2' => 'BQ', 'iso3' => 'BES', 'numcode' => '535', 'calling_code' => '599', 'nationality' => 'Bonairean']);
        Country::insert(['name' => 'Bosnia and Herzegovina', 'long_name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'numcode' => '70', 'calling_code' => '387', 'nationality' => 'Bosnian']);
        Country::insert(['name' => 'Botswana', 'long_name' => 'Republic of Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'numcode' => '72', 'calling_code' => '267', 'nationality' => 'Motswana']);
        Country::insert(['name' => 'Bouvet Island', 'long_name' => 'Bouvet Island', 'iso2' => 'BV', 'iso3' => 'BVT', 'numcode' => '74', 'calling_code' => 'NONE', 'nationality' => 'Bouvet Islan']);
        Country::insert(['name' => 'Brazil', 'long_name' => 'Federative Republic of Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'numcode' => '76', 'calling_code' => '55', 'nationality' => 'Brazilian']);
        Country::insert(['name' => 'British Indian Ocean Territory', 'long_name' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'numcode' => '86', 'calling_code' => '246', 'nationality' => 'British IOT']);
        Country::insert(['name' => 'Brunei', 'long_name' => 'Brunei Darussalam', 'iso2' => 'BN', 'iso3' => 'BRN', 'numcode' => '96', 'calling_code' => '673', 'nationality' => 'Bruneian']);
        Country::insert(['name' => 'Bulgaria', 'long_name' => 'Republic of Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'numcode' => '100', 'calling_code' => '359', 'nationality' => 'Bulgarian']);
        Country::insert(['name' => 'Burkina Faso', 'long_name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'numcode' => '854', 'calling_code' => '226', 'nationality' => 'Burkinabe']);
        Country::insert(['name' => 'Burundi', 'long_name' => 'Republic of Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'numcode' => '108', 'calling_code' => '257', 'nationality' => 'Burundian']);
        Country::insert(['name' => 'Cambodia', 'long_name' => 'Kingdom of Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'numcode' => '116', 'calling_code' => '855', 'nationality' => 'Cambodian']);
        Country::insert(['name' => 'Cameroon', 'long_name' => 'Republic of Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'numcode' => '120', 'calling_code' => '237', 'nationality' => 'Cameroonian']);
        Country::insert(['name' => 'Canada', 'long_name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'numcode' => '124', 'calling_code' => '1', 'nationality' => 'Canadian']);
        Country::insert(['name' => 'Cape Verde', 'long_name' => 'Republic of Cape Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'numcode' => '132', 'calling_code' => '238', 'nationality' => 'Cape Verdean']);
        Country::insert(['name' => 'Cayman Islands', 'long_name' => 'The Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'numcode' => '136', 'calling_code' => '1+345', 'nationality' => 'Caymanian']);
        Country::insert(['name' => 'Central African Republic', 'long_name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'numcode' => '140', 'calling_code' => '236', 'nationality' => 'Central Afri']);
        Country::insert(['name' => 'Chad', 'long_name' => 'Republic of Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'numcode' => '148', 'calling_code' => '235', 'nationality' => 'Chadian']);
        Country::insert(['name' => 'Chile', 'long_name' => 'Republic of Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'numcode' => '152', 'calling_code' => '56', 'nationality' => 'Chilean']);
        Country::insert(['name' => 'China', 'long_name' => 'People\'s Republic of China', 'iso2' => 'CN', 'iso3' => 'CHN', 'numcode' => '156', 'calling_code' => '86', 'nationality' => 'Chinese']);
        Country::insert(['name' => 'Christmas Island', 'long_name' => 'Christmas Island', 'iso2' => 'CX', 'iso3' => 'CXR', 'numcode' => '162', 'calling_code' => '61', 'nationality' => 'Christmas Is']);
        Country::insert(['name' => 'Cocos (Keeling) Islands', 'long_name' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'numcode' => '166', 'calling_code' => '61', 'nationality' => 'Cocos Island']);
        Country::insert(['name' => 'Colombia', 'long_name' => 'Republic of Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'numcode' => '170', 'calling_code' => '57', 'nationality' => 'Colombian']);
        Country::insert(['name' => 'Comoros', 'long_name' => 'Union of the Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'numcode' => '174', 'calling_code' => '269', 'nationality' => 'Comoran']);
        Country::insert(['name' => 'Congo', 'long_name' => 'Republic of the Congo', 'iso2' => 'CG', 'iso3' => 'COG', 'numcode' => '178', 'calling_code' => '242', 'nationality' => 'Congolese']);
        Country::insert(['name' => 'Cook Islands', 'long_name' => 'Cook Islands', 'iso2' => 'CK', 'iso3' => 'COK', 'numcode' => '184', 'calling_code' => '682', 'nationality' => 'Cook Islande']);
        Country::insert(['name' => 'Costa Rica', 'long_name' => 'Republic of Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'numcode' => '188', 'calling_code' => '506', 'nationality' => 'Costa Rican']);
        Country::insert(['name' => 'Cote d\'ivoire (Ivory Coast)', 'long_name' => 'Republic of C&ocirc;te D\'Ivoire (Ivory Coast)', 'iso2' => 'CI', 'iso3' => 'CIV', 'numcode' => '384', 'calling_code' => '225', 'nationality' => 'Ivorian']);
        Country::insert(['name' => 'Croatia', 'long_name' => 'Republic of Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'numcode' => '191', 'calling_code' => '385', 'nationality' => 'Croatian']);
        Country::insert(['name' => 'Cuba', 'long_name' => 'Republic of Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'numcode' => '192', 'calling_code' => '53', 'nationality' => 'Cuban']);
        Country::insert(['name' => 'Curacao', 'long_name' => 'Cura&ccedil;ao', 'iso2' => 'CW', 'iso3' => 'CUW', 'numcode' => '531', 'calling_code' => '599', 'nationality' => 'Curaçaoan']);
        Country::insert(['name' => 'Cyprus', 'long_name' => 'Republic of Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'numcode' => '196', 'calling_code' => '357', 'nationality' => 'Cypriot']);
        Country::insert(['name' => 'Czech Republic', 'long_name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'numcode' => '203', 'calling_code' => '420', 'nationality' => 'Czech']);
        Country::insert(['name' => 'Democratic Republic of the Congo', 'long_name' => 'Democratic Republic of the Congo', 'iso2' => 'CD', 'iso3' => 'COD', 'numcode' => '180', 'calling_code' => '243', 'nationality' => 'of the Democ']);
        Country::insert(['name' => 'Denmark', 'long_name' => 'Kingdom of Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'numcode' => '208', 'calling_code' => '45', 'nationality' => 'Danish']);
        Country::insert(['name' => 'Djibouti', 'long_name' => 'Republic of Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'numcode' => '262', 'calling_code' => '253', 'nationality' => 'Djiboutian']);
        Country::insert(['name' => 'Dominica', 'long_name' => 'Commonwealth of Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'numcode' => '212', 'calling_code' => '1+767', 'nationality' => 'Dominican']);
        Country::insert(['name' => 'Dominican Republic', 'long_name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'numcode' => '214', 'calling_code' => '1+809, 8', 'nationality' => 'Dominican']);
        Country::insert(['name' => 'Ecuador', 'long_name' => 'Republic of Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'numcode' => '218', 'calling_code' => '593', 'nationality' => 'Ecuadorian']);
        Country::insert(['name' => 'Egypt', 'long_name' => 'Arab Republic of Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'numcode' => '818', 'calling_code' => '20', 'nationality' => 'Egyptian']);
        Country::insert(['name' => 'El Salvador', 'long_name' => 'Republic of El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'numcode' => '222', 'calling_code' => '503', 'nationality' => 'Salvadoran']);
        Country::insert(['name' => 'Equatorial Guinea', 'long_name' => 'Republic of Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'numcode' => '226', 'calling_code' => '240', 'nationality' => 'Equatoguinea']);
        Country::insert(['name' => 'Eritrea', 'long_name' => 'State of Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'numcode' => '232', 'calling_code' => '291', 'nationality' => 'Eritrean']);
        Country::insert(['name' => 'Estonia', 'long_name' => 'Republic of Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'numcode' => '233', 'calling_code' => '372', 'nationality' => 'Estonian']);
        Country::insert(['name' => 'Ethiopia', 'long_name' => 'Federal Democratic Republic of Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'numcode' => '231', 'calling_code' => '251', 'nationality' => 'Ethiopian']);
        Country::insert(['name' => 'Falkland Islands (Malvinas)', 'long_name' => 'The Falkland Islands (Malvinas)', 'iso2' => 'FK', 'iso3' => 'FLK', 'numcode' => '238', 'calling_code' => '500', 'nationality' => 'Falkland Isl']);
        Country::insert(['name' => 'Faroe Islands', 'long_name' => 'The Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'numcode' => '234', 'calling_code' => '298', 'nationality' => 'Faeroese']);
        Country::insert(['name' => 'Fiji', 'long_name' => 'Republic of Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'numcode' => '242', 'calling_code' => '679', 'nationality' => 'Fijian']);
        Country::insert(['name' => 'Finland', 'long_name' => 'Republic of Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'numcode' => '246', 'calling_code' => '358', 'nationality' => 'Finnish']);
        Country::insert(['name' => 'France', 'long_name' => 'French Republic', 'iso2' => 'FR', 'iso3' => 'FRA', 'numcode' => '250', 'calling_code' => '33', 'nationality' => 'French']);
        Country::insert(['name' => 'French Guiana', 'long_name' => 'French Guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'numcode' => '254', 'calling_code' => '594', 'nationality' => 'Guianese']);
        Country::insert(['name' => 'French Polynesia', 'long_name' => 'French Polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'numcode' => '258', 'calling_code' => '689', 'nationality' => 'Polynesian']);
        Country::insert(['name' => 'French Southern Territories', 'long_name' => 'French Southern Territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'numcode' => '260', 'calling_code' => '\N', 'nationality' => 'French Southern Territories']);
        Country::insert(['name' => 'Gabon', 'long_name' => 'Gabonese Republic', 'iso2' => 'GA', 'iso3' => 'GAB', 'numcode' => '266', 'calling_code' => '241', 'nationality' => 'Gabonese']);
        Country::insert(['name' => 'Gambia', 'long_name' => 'Republic of The Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'numcode' => '270', 'calling_code' => '220', 'nationality' => 'Gambian']);
        Country::insert(['name' => 'Georgia', 'long_name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'numcode' => '268', 'calling_code' => '995', 'nationality' => 'Georgian']);
        Country::insert(['name' => 'Germany', 'long_name' => 'Federal Republic of Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'numcode' => '276', 'calling_code' => '49', 'nationality' => 'German']);
        Country::insert(['name' => 'Ghana', 'long_name' => 'Republic of Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'numcode' => '288', 'calling_code' => '233', 'nationality' => 'Ghanaian']);
        Country::insert(['name' => 'Gibraltar', 'long_name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'numcode' => '292', 'calling_code' => '350', 'nationality' => 'Gibraltarian']);
        Country::insert(['name' => 'Greece', 'long_name' => 'Hellenic Republic', 'iso2' => 'GR', 'iso3' => 'GRC', 'numcode' => '300', 'calling_code' => '30', 'nationality' => 'Greek']);
        Country::insert(['name' => 'Greenland', 'long_name' => 'Greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'numcode' => '304', 'calling_code' => '299', 'nationality' => 'Greenlander']);
        Country::insert(['name' => 'Grenada', 'long_name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'numcode' => '308', 'calling_code' => '1+473', 'nationality' => 'Grenadian']);
        Country::insert(['name' => 'Guadaloupe', 'long_name' => 'Guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'numcode' => '312', 'calling_code' => '590', 'nationality' => 'Guadeloupean']);
        Country::insert(['name' => 'Guam', 'long_name' => 'Guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'numcode' => '316', 'calling_code' => '1+671', 'nationality' => 'Guamanian']);
        Country::insert(['name' => 'Guatemala', 'long_name' => 'Republic of Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'numcode' => '320', 'calling_code' => '502', 'nationality' => 'Guatemalan']);
        Country::insert(['name' => 'Guernsey', 'long_name' => 'Guernsey', 'iso2' => 'GG', 'iso3' => 'GGY', 'numcode' => '831', 'calling_code' => '44', 'nationality' => 'of Guernsey']);
        Country::insert(['name' => 'Guinea', 'long_name' => 'Republic of Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'numcode' => '324', 'calling_code' => '224', 'nationality' => 'Guinean']);
        Country::insert(['name' => 'Guinea-Bissau', 'long_name' => 'Republic of Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'numcode' => '624', 'calling_code' => '245', 'nationality' => 'Guinea-Bissa']);
        Country::insert(['name' => 'Guyana', 'long_name' => 'Co-operative Republic of Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'numcode' => '328', 'calling_code' => '592', 'nationality' => 'Guyanese']);
        Country::insert(['name' => 'Haiti', 'long_name' => 'Republic of Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'numcode' => '332', 'calling_code' => '509', 'nationality' => 'Haitian']);
        Country::insert(['name' => 'Heard Island and McDonald Islands', 'long_name' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'iso3' => 'HMD', 'numcode' => '334', 'calling_code' => 'NONE', 'nationality' => 'Heard Island and McDonald Islands']);
        Country::insert(['name' => 'Honduras', 'long_name' => 'Republic of Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'numcode' => '340', 'calling_code' => '504', 'nationality' => 'Honduran']);
        Country::insert(['name' => 'Hong Kong', 'long_name' => 'Hong Kong', 'iso2' => 'HK', 'iso3' => 'HKG', 'numcode' => '344', 'calling_code' => '852', 'nationality' => 'Hong Kong Ch']);
        Country::insert(['name' => 'Hungary', 'long_name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'numcode' => '348', 'calling_code' => '36', 'nationality' => 'Hungarian']);
        Country::insert(['name' => 'Iceland', 'long_name' => 'Republic of Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'numcode' => '352', 'calling_code' => '354', 'nationality' => 'Icelandic']);
        Country::insert(['name' => 'India', 'long_name' => 'Republic of India', 'iso2' => 'IN', 'iso3' => 'IND', 'numcode' => '356', 'calling_code' => '91', 'nationality' => 'Indian']);
        Country::insert(['name' => 'Indonesia', 'long_name' => 'Republic of Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'numcode' => '360', 'calling_code' => '62', 'nationality' => 'Indonesian']);
        Country::insert(['name' => 'Iran', 'long_name' => 'Islamic Republic of Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'numcode' => '364', 'calling_code' => '98', 'nationality' => 'Iranian']);
        Country::insert(['name' => 'Iraq', 'long_name' => 'Republic of Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'numcode' => '368', 'calling_code' => '964', 'nationality' => 'Iraqi']);
        Country::insert(['name' => 'Ireland', 'long_name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'numcode' => '372', 'calling_code' => '353', 'nationality' => 'Irish']);
        Country::insert(['name' => 'Isle of Man', 'long_name' => 'Isle of Man', 'iso2' => 'IM', 'iso3' => 'IMN', 'numcode' => '833', 'calling_code' => '44', 'nationality' => 'Manxman; Man']);
        Country::insert(['name' => 'Israel', 'long_name' => 'State of Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'numcode' => '376', 'calling_code' => '972', 'nationality' => 'Israeli']);
        Country::insert(['name' => 'Italy', 'long_name' => 'Italian Republic', 'iso2' => 'IT', 'iso3' => 'ITA', 'numcode' => '380', 'calling_code' => '39', 'nationality' => 'Italian']);
        Country::insert(['name' => 'Jamaica', 'long_name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'numcode' => '388', 'calling_code' => '1+876', 'nationality' => 'Jamaican']);
        Country::insert(['name' => 'Japan', 'long_name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'numcode' => '392', 'calling_code' => '81', 'nationality' => 'Japanese']);
        Country::insert(['name' => 'Jersey', 'long_name' => 'The Bailiwick of Jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'numcode' => '832', 'calling_code' => '44', 'nationality' => 'of Jersey']);
        Country::insert(['name' => 'Jordan', 'long_name' => 'Hashemite Kingdom of Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'numcode' => '400', 'calling_code' => '962', 'nationality' => 'Jordanian']);
        Country::insert(['name' => 'Kazakhstan', 'long_name' => 'Republic of Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'numcode' => '398', 'calling_code' => '7', 'nationality' => 'Kazakhstani']);
        Country::insert(['name' => 'Kenya', 'long_name' => 'Republic of Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'numcode' => '404', 'calling_code' => '254', 'nationality' => 'Kenyan']);
        Country::insert(['name' => 'Kiribati', 'long_name' => 'Republic of Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'numcode' => '296', 'calling_code' => '686', 'nationality' => 'I-Kiribati']);
        Country::insert(['name' => 'Kosovo', 'long_name' => 'Republic of Kosovo', 'iso2' => 'XK', 'iso3' => '---', 'numcode' => '---', 'calling_code' => '381', 'nationality' => 'Kosovian']);
        Country::insert(['name' => 'Kuwait', 'long_name' => 'State of Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'numcode' => '414', 'calling_code' => '965', 'nationality' => 'Kuwaiti']);
        Country::insert(['name' => 'Kyrgyzstan', 'long_name' => 'Kyrgyz Republic', 'iso2' => 'KG', 'iso3' => 'KGZ', 'numcode' => '417', 'calling_code' => '996', 'nationality' => 'Kyrgyzstani']);
        Country::insert(['name' => 'Laos', 'long_name' => 'Lao People\'s Democratic Republic', 'iso2' => 'LA', 'iso3' => 'LAO', 'numcode' => '418', 'calling_code' => '856', 'nationality' => 'Laotian']);
        Country::insert(['name' => 'Latvia', 'long_name' => 'Republic of Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'numcode' => '428', 'calling_code' => '371', 'nationality' => 'Latvian']);
        Country::insert(['name' => 'Lebanon', 'long_name' => 'Republic of Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'numcode' => '422', 'calling_code' => '961', 'nationality' => 'Lebanese']);
        Country::insert(['name' => 'Lesotho', 'long_name' => 'Kingdom of Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'numcode' => '426', 'calling_code' => '266', 'nationality' => 'Basotho']);
        Country::insert(['name' => 'Liberia', 'long_name' => 'Republic of Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'numcode' => '430', 'calling_code' => '231', 'nationality' => 'Liberian']);
        Country::insert(['name' => 'Libya', 'long_name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'numcode' => '434', 'calling_code' => '218', 'nationality' => 'Libyan']);
        Country::insert(['name' => 'Liechtenstein', 'long_name' => 'Principality of Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'numcode' => '438', 'calling_code' => '423', 'nationality' => 'Liechtenstei']);
        Country::insert(['name' => 'Lithuania', 'long_name' => 'Republic of Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'numcode' => '440', 'calling_code' => '370', 'nationality' => 'Lithuanian']);
        Country::insert(['name' => 'Luxembourg', 'long_name' => 'Grand Duchy of Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'numcode' => '442', 'calling_code' => '352', 'nationality' => 'Luxembourg']);
        Country::insert(['name' => 'Macao', 'long_name' => 'The Macao Special Administrative Region', 'iso2' => 'MO', 'iso3' => 'MAC', 'numcode' => '446', 'calling_code' => '853', 'nationality' => 'Macanese']);
        Country::insert(['name' => 'Macedonia', 'long_name' => 'The Former Yugoslav Republic of Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'numcode' => '807', 'calling_code' => '389', 'nationality' => 'Macedonian']);
        Country::insert(['name' => 'Madagascar', 'long_name' => 'Republic of Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'numcode' => '450', 'calling_code' => '261', 'nationality' => 'Malagasy']);
        Country::insert(['name' => 'Malawi', 'long_name' => 'Republic of Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'numcode' => '454', 'calling_code' => '265', 'nationality' => 'Malawian']);
        Country::insert(['name' => 'Malaysia', 'long_name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'numcode' => '458', 'calling_code' => '60', 'nationality' => 'Malaysian']);
        Country::insert(['name' => 'Maldives', 'long_name' => 'Republic of Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'numcode' => '462', 'calling_code' => '960', 'nationality' => 'Maldivian']);
        Country::insert(['name' => 'Mali', 'long_name' => 'Republic of Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'numcode' => '466', 'calling_code' => '223', 'nationality' => 'Malian']);
        Country::insert(['name' => 'Malta', 'long_name' => 'Republic of Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'numcode' => '470', 'calling_code' => '356', 'nationality' => 'Maltese']);
        Country::insert(['name' => 'Marshall Islands', 'long_name' => 'Republic of the Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'numcode' => '584', 'calling_code' => '692', 'nationality' => 'Marshallese']);
        Country::insert(['name' => 'Martinique', 'long_name' => 'Martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'numcode' => '474', 'calling_code' => '596', 'nationality' => 'Martinican']);
        Country::insert(['name' => 'Mauritania', 'long_name' => 'Islamic Republic of Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'numcode' => '478', 'calling_code' => '222', 'nationality' => 'Mauritanian']);
        Country::insert(['name' => 'Mauritius', 'long_name' => 'Republic of Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'numcode' => '480', 'calling_code' => '230', 'nationality' => 'Mauritian']);
        Country::insert(['name' => 'Mayotte', 'long_name' => 'Mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'numcode' => '175', 'calling_code' => '262', 'nationality' => 'Mahorais']);
        Country::insert(['name' => 'Mexico', 'long_name' => 'United Mexican States', 'iso2' => 'MX', 'iso3' => 'MEX', 'numcode' => '484', 'calling_code' => '52', 'nationality' => 'Mexican']);
        Country::insert(['name' => 'Micronesia', 'long_name' => 'Federated States of Micronesia', 'iso2' => 'FM', 'iso3' => 'FSM', 'numcode' => '583', 'calling_code' => '691', 'nationality' => 'Micronesian']);
        Country::insert(['name' => 'Moldava', 'long_name' => 'Republic of Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'numcode' => '498', 'calling_code' => '373', 'nationality' => 'Moldovan']);
        Country::insert(['name' => 'Monaco', 'long_name' => 'Principality of Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'numcode' => '492', 'calling_code' => '377', 'nationality' => 'Monegasque']);
        Country::insert(['name' => 'Mongolia', 'long_name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'numcode' => '496', 'calling_code' => '976', 'nationality' => 'Mongolian']);
        Country::insert(['name' => 'Montenegro', 'long_name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'numcode' => '499', 'calling_code' => '382', 'nationality' => 'Montenegrin']);
        Country::insert(['name' => 'Montserrat', 'long_name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'numcode' => '500', 'calling_code' => '1+664', 'nationality' => 'Montserratia']);
        Country::insert(['name' => 'Morocco', 'long_name' => 'Kingdom of Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'numcode' => '504', 'calling_code' => '212', 'nationality' => 'Moroccan']);
        Country::insert(['name' => 'Mozambique', 'long_name' => 'Republic of Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'numcode' => '508', 'calling_code' => '258', 'nationality' => 'Mozambican']);
        Country::insert(['name' => 'Myanmar (Burma)', 'long_name' => 'Republic of the Union of Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'numcode' => '104', 'calling_code' => '95', 'nationality' => 'of Myanmar/B']);
        Country::insert(['name' => 'Namibia', 'long_name' => 'Republic of Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'numcode' => '516', 'calling_code' => '264', 'nationality' => 'Namibian']);
        Country::insert(['name' => 'Nauru', 'long_name' => 'Republic of Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'numcode' => '520', 'calling_code' => '674', 'nationality' => 'Nauruan']);
        Country::insert(['name' => 'Nepal', 'long_name' => 'Federal Democratic Republic of Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'numcode' => '524', 'calling_code' => '977', 'nationality' => 'Nepalese']);
        Country::insert(['name' => 'Netherlands', 'long_name' => 'Kingdom of the Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'numcode' => '528', 'calling_code' => '31', 'nationality' => 'Dutch']);
        Country::insert(['name' => 'New Caledonia', 'long_name' => 'New Caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'numcode' => '540', 'calling_code' => '687', 'nationality' => 'New Caledoni']);
        Country::insert(['name' => 'New Zealand', 'long_name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'numcode' => '554', 'calling_code' => '64', 'nationality' => 'New Zealand']);
        Country::insert(['name' => 'Nicaragua', 'long_name' => 'Republic of Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'numcode' => '558', 'calling_code' => '505', 'nationality' => 'Nicaraguan']);
        Country::insert(['name' => 'Niger', 'long_name' => 'Republic of Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'numcode' => '562', 'calling_code' => '227', 'nationality' => 'Nigerien']);
        Country::insert(['name' => 'Nigeria', 'long_name' => 'Federal Republic of Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'numcode' => '566', 'calling_code' => '234', 'nationality' => 'Nigerian']);
        Country::insert(['name' => 'Niue', 'long_name' => 'Niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'numcode' => '570', 'calling_code' => '683', 'nationality' => 'Niuean']);
        Country::insert(['name' => 'Norfolk Island', 'long_name' => 'Norfolk Island', 'iso2' => 'NF', 'iso3' => 'NFK', 'numcode' => '574', 'calling_code' => '672', 'nationality' => 'Norfolk Isla']);
        Country::insert(['name' => 'North Korea', 'long_name' => 'Democratic People\'s Republic of Korea', 'iso2' => 'KP', 'iso3' => 'PRK', 'numcode' => '408', 'calling_code' => '850', 'nationality' => 'North Korean']);
        Country::insert(['name' => 'Northern Mariana Islands', 'long_name' => 'Northern Mariana Islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'numcode' => '580', 'calling_code' => '1+670', 'nationality' => 'Northern Mar']);
        Country::insert(['name' => 'Norway', 'long_name' => 'Kingdom of Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'numcode' => '578', 'calling_code' => '47', 'nationality' => 'Norwegian']);
        Country::insert(['name' => 'Oman', 'long_name' => 'Sultanate of Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'numcode' => '512', 'calling_code' => '968', 'nationality' => 'Omani']);
        Country::insert(['name' => 'Pakistan', 'long_name' => 'Islamic Republic of Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'numcode' => '586', 'calling_code' => '92', 'nationality' => 'Pakistani']);
        Country::insert(['name' => 'Palau', 'long_name' => 'Republic of Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'numcode' => '585', 'calling_code' => '680', 'nationality' => 'Palauan']);
        Country::insert(['name' => 'Palestine', 'long_name' => 'State of Palestine (or Occupied Palestinian Territory)', 'iso2' => 'PS', 'iso3' => 'PSE', 'numcode' => '275', 'calling_code' => '970', 'nationality' => 'Palestinian']);
        Country::insert(['name' => 'Panama', 'long_name' => 'Republic of Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'numcode' => '591', 'calling_code' => '507', 'nationality' => 'Panamanian']);
        Country::insert(['name' => 'Papua New Guinea', 'long_name' => 'Independent State of Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'numcode' => '598', 'calling_code' => '675', 'nationality' => 'Papua New Gu']);
        Country::insert(['name' => 'Paraguay', 'long_name' => 'Republic of Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'numcode' => '600', 'calling_code' => '595', 'nationality' => 'Paraguayan']);
        Country::insert(['name' => 'Peru', 'long_name' => 'Republic of Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'numcode' => '604', 'calling_code' => '51', 'nationality' => 'Peruvian']);
        Country::insert(['name' => 'Phillipines', 'long_name' => 'Republic of the Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'numcode' => '608', 'calling_code' => '63', 'nationality' => 'Filipino']);
        Country::insert(['name' => 'Pitcairn', 'long_name' => 'Pitcairn', 'iso2' => 'PN', 'iso3' => 'PCN', 'numcode' => '612', 'calling_code' => 'NONE', 'nationality' => 'Pitcairner']);
        Country::insert(['name' => 'Poland', 'long_name' => 'Republic of Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'numcode' => '616', 'calling_code' => '48', 'nationality' => 'Polish']);
        Country::insert(['name' => 'Portugal', 'long_name' => 'Portuguese Republic', 'iso2' => 'PT', 'iso3' => 'PRT', 'numcode' => '620', 'calling_code' => '351', 'nationality' => 'Portuguese']);
        Country::insert(['name' => 'Puerto Rico', 'long_name' => 'Commonwealth of Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'numcode' => '630', 'calling_code' => '1+939', 'nationality' => 'Puerto Rican']);
        Country::insert(['name' => 'Qatar', 'long_name' => 'State of Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'numcode' => '634', 'calling_code' => '974', 'nationality' => 'Qatari']);
        Country::insert(['name' => 'Reunion', 'long_name' => 'R&eacute;union', 'iso2' => 'RE', 'iso3' => 'REU', 'numcode' => '638', 'calling_code' => '262', 'nationality' => 'Reunionese']);
        Country::insert(['name' => 'Romania', 'long_name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'numcode' => '642', 'calling_code' => '40', 'nationality' => 'Romanian']);
        Country::insert(['name' => 'Russia', 'long_name' => 'Russian Federation', 'iso2' => 'RU', 'iso3' => 'RUS', 'numcode' => '643', 'calling_code' => '7', 'nationality' => 'Russian']);
        Country::insert(['name' => 'Rwanda', 'long_name' => 'Republic of Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'numcode' => '646', 'calling_code' => '250', 'nationality' => 'Rwandan']);
        Country::insert(['name' => 'Saint Barthelemy', 'long_name' => 'Saint Barth&eacute;lemy', 'iso2' => 'BL', 'iso3' => 'BLM', 'numcode' => '652', 'calling_code' => '590', 'nationality' => 'of Saint Bar']);
        Country::insert(['name' => 'Saint Helena', 'long_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso2' => 'SH', 'iso3' => 'SHN', 'numcode' => '654', 'calling_code' => '290', 'nationality' => 'of Saint Hel']);
        Country::insert(['name' => 'Saint Kitts and Nevis', 'long_name' => 'Federation of Saint Christopher and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'numcode' => '659', 'calling_code' => '1+869', 'nationality' => 'Kittitian']);
        Country::insert(['name' => 'Saint Lucia', 'long_name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'numcode' => '662', 'calling_code' => '1+758', 'nationality' => 'Saint Lucian']);
        Country::insert(['name' => 'Saint Martin', 'long_name' => 'Saint Martin', 'iso2' => 'MF', 'iso3' => 'MAF', 'numcode' => '663', 'calling_code' => '590', 'nationality' => 'of Saint Mar']);
        Country::insert(['name' => 'Saint Pierre and Miquelon', 'long_name' => 'Saint Pierre and Miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'numcode' => '666', 'calling_code' => '508', 'nationality' => 'St-Pierrais;']);
        Country::insert(['name' => 'Saint Vincent and the Grenadines', 'long_name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'numcode' => '670', 'calling_code' => '1+784', 'nationality' => 'Vincentian']);
        Country::insert(['name' => 'Samoa', 'long_name' => 'Independent State of Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'numcode' => '882', 'calling_code' => '685', 'nationality' => 'Samoan']);
        Country::insert(['name' => 'San Marino', 'long_name' => 'Republic of San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'numcode' => '674', 'calling_code' => '378', 'nationality' => 'Sammarinese']);
        Country::insert(['name' => 'Sao Tome and Principe', 'long_name' => 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'iso2' => 'ST', 'iso3' => 'STP', 'numcode' => '678', 'calling_code' => '239', 'nationality' => 'Sao Tomean']);
        Country::insert(['name' => 'Saudi Arabia', 'long_name' => 'Kingdom of Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'numcode' => '682', 'calling_code' => '966', 'nationality' => 'Saudi']);
        Country::insert(['name' => 'Senegal', 'long_name' => 'Republic of Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'numcode' => '686', 'calling_code' => '221', 'nationality' => 'Senegalese']);
        Country::insert(['name' => 'Serbia', 'long_name' => 'Republic of Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'numcode' => '688', 'calling_code' => '381', 'nationality' => 'Serbian']);
        Country::insert(['name' => 'Seychelles', 'long_name' => 'Republic of Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'numcode' => '690', 'calling_code' => '248', 'nationality' => 'Seychellois']);
        Country::insert(['name' => 'Sierra Leone', 'long_name' => 'Republic of Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'numcode' => '694', 'calling_code' => '232', 'nationality' => 'Sierra Leone']);
        Country::insert(['name' => 'Singapore', 'long_name' => 'Republic of Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'numcode' => '702', 'calling_code' => '65', 'nationality' => 'Singapore']);
        Country::insert(['name' => 'Sint Maarten', 'long_name' => 'Sint Maarten', 'iso2' => 'SX', 'iso3' => 'SXM', 'numcode' => '534', 'calling_code' => '1+721', 'nationality' => 'Sint Maarten']);
        Country::insert(['name' => 'Slovakia', 'long_name' => 'Slovak Republic', 'iso2' => 'SK', 'iso3' => 'SVK', 'numcode' => '703', 'calling_code' => '421', 'nationality' => 'Slovak']);
        Country::insert(['name' => 'Slovenia', 'long_name' => 'Republic of Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'numcode' => '705', 'calling_code' => '386', 'nationality' => 'Slovenian']);
        Country::insert(['name' => 'Solomon Islands', 'long_name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'numcode' => '90', 'calling_code' => '677', 'nationality' => 'Solomon Isla']);
        Country::insert(['name' => 'Somalia', 'long_name' => 'Somali Republic', 'iso2' => 'SO', 'iso3' => 'SOM', 'numcode' => '706', 'calling_code' => '252', 'nationality' => 'Somali']);
        Country::insert(['name' => 'South Africa', 'long_name' => 'Republic of South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'numcode' => '710', 'calling_code' => '27', 'nationality' => 'South Africa']);
        Country::insert(['name' => 'South Georgia and the South Sandwich Islands', 'long_name' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'iso3' => 'SGS', 'numcode' => '239', 'calling_code' => '500', 'nationality' => 'South Georgian South Sandwich Islander']);
        Country::insert(['name' => 'South Korea', 'long_name' => 'Republic of Korea', 'iso2' => 'KR', 'iso3' => 'KOR', 'numcode' => '410', 'calling_code' => '82', 'nationality' => 'South Korean']);
        Country::insert(['name' => 'South Sudan', 'long_name' => 'Republic of South Sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'numcode' => '728', 'calling_code' => '211', 'nationality' => 'South Sudane']);
        Country::insert(['name' => 'Spain', 'long_name' => 'Kingdom of Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'numcode' => '724', 'calling_code' => '34', 'nationality' => 'Spanish']);
        Country::insert(['name' => 'Sri Lanka', 'long_name' => 'Democratic Socialist Republic of Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'numcode' => '144', 'calling_code' => '94', 'nationality' => 'Sri Lankan']);
        Country::insert(['name' => 'Sudan', 'long_name' => 'Republic of the Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'numcode' => '729', 'calling_code' => '249', 'nationality' => 'Sudanese']);
        Country::insert(['name' => 'Suriname', 'long_name' => 'Republic of Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'numcode' => '740', 'calling_code' => '597', 'nationality' => 'Surinamese']);
        Country::insert(['name' => 'Svalbard and Jan Mayen', 'long_name' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'iso3' => 'SJM', 'numcode' => '744', 'calling_code' => '47', 'nationality' => 'of Svalbard,']);
        Country::insert(['name' => 'Swaziland', 'long_name' => 'Kingdom of Swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'numcode' => '748', 'calling_code' => '268', 'nationality' => 'Swazi']);
        Country::insert(['name' => 'Sweden', 'long_name' => 'Kingdom of Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'numcode' => '752', 'calling_code' => '46', 'nationality' => 'Swedish']);
        Country::insert(['name' => 'Switzerland', 'long_name' => 'Swiss Confederation', 'iso2' => 'CH', 'iso3' => 'CHE', 'numcode' => '756', 'calling_code' => '41', 'nationality' => 'Swiss']);
        Country::insert(['name' => 'Syria', 'long_name' => 'Syrian Arab Republic', 'iso2' => 'SY', 'iso3' => 'SYR', 'numcode' => '760', 'calling_code' => '963', 'nationality' => 'Syrian']);
        Country::insert(['name' => 'Taiwan', 'long_name' => 'Republic of China (Taiwan)', 'iso2' => 'TW', 'iso3' => 'TWN', 'numcode' => '158', 'calling_code' => '886', 'nationality' => 'Taiwanese']);
        Country::insert(['name' => 'Tajikistan', 'long_name' => 'Republic of Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'numcode' => '762', 'calling_code' => '992', 'nationality' => 'Tajikistani']);
        Country::insert(['name' => 'Tanzania', 'long_name' => 'United Republic of Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'numcode' => '834', 'calling_code' => '255', 'nationality' => 'Tanzanian']);
        Country::insert(['name' => 'Thailand', 'long_name' => 'Kingdom of Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'numcode' => '764', 'calling_code' => '66', 'nationality' => 'Thai']);
        Country::insert(['name' => 'Timor-Leste (East Timor)', 'long_name' => 'Democratic Republic of Timor-Leste', 'iso2' => 'TL', 'iso3' => 'TLS', 'numcode' => '626', 'calling_code' => '670', 'nationality' => 'East Timores']);
        Country::insert(['name' => 'Togo', 'long_name' => 'Togolese Republic', 'iso2' => 'TG', 'iso3' => 'TGO', 'numcode' => '768', 'calling_code' => '228', 'nationality' => 'Togolese']);
        Country::insert(['name' => 'Tokelau', 'long_name' => 'Tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'numcode' => '772', 'calling_code' => '690', 'nationality' => 'Tokelauan']);
        Country::insert(['name' => 'Tonga', 'long_name' => 'Kingdom of Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'numcode' => '776', 'calling_code' => '676', 'nationality' => 'Tongan']);
        Country::insert(['name' => 'Trinidad and Tobago', 'long_name' => 'Republic of Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'numcode' => '780', 'calling_code' => '1+868', 'nationality' => 'Trinidadian']);
        Country::insert(['name' => 'Tunisia', 'long_name' => 'Republic of Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'numcode' => '788', 'calling_code' => '216', 'nationality' => 'Tunisian']);
        Country::insert(['name' => 'Turkey', 'long_name' => 'Republic of Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'numcode' => '792', 'calling_code' => '90', 'nationality' => 'Turkish']);
        Country::insert(['name' => 'Turkmenistan', 'long_name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'numcode' => '795', 'calling_code' => '993', 'nationality' => 'Turkmen']);
        Country::insert(['name' => 'Turks and Caicos Islands', 'long_name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'numcode' => '796', 'calling_code' => '1+649', 'nationality' => 'Turks and Ca']);
        Country::insert(['name' => 'Tuvalu', 'long_name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'numcode' => '798', 'calling_code' => '688', 'nationality' => 'Tuvaluan']);
        Country::insert(['name' => 'Uganda', 'long_name' => 'Republic of Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'numcode' => '800', 'calling_code' => '256', 'nationality' => 'Ugandan']);
        Country::insert(['name' => 'Ukraine', 'long_name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'numcode' => '804', 'calling_code' => '380', 'nationality' => 'Ukrainian']);
        Country::insert(['name' => 'United Arab Emirates', 'long_name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'numcode' => '784', 'calling_code' => '971', 'nationality' => 'Emirati']);
        Country::insert(['name' => 'United Kingdom', 'long_name' => 'United Kingdom of Great Britain and Nothern Ireland', 'iso2' => 'GB', 'iso3' => 'GBR', 'numcode' => '826', 'calling_code' => '44', 'nationality' => 'British']);
        Country::insert(['name' => 'United States', 'long_name' => 'United States of America', 'iso2' => 'US', 'iso3' => 'USA', 'numcode' => '840', 'calling_code' => '1', 'nationality' => 'American']);
        Country::insert(['name' => 'United States Minor Outlying Islands', 'long_name' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'numcode' => '581', 'calling_code' => 'NONE', 'nationality' => 'American Islander']);
        Country::insert(['name' => 'Uruguay', 'long_name' => 'Eastern Republic of Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'numcode' => '858', 'calling_code' => '598', 'nationality' => 'Uruguayan']);
        Country::insert(['name' => 'Uzbekistan', 'long_name' => 'Republic of Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'numcode' => '860', 'calling_code' => '998', 'nationality' => 'Uzbek']);
        Country::insert(['name' => 'Vanuatu', 'long_name' => 'Republic of Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'numcode' => '548', 'calling_code' => '678', 'nationality' => 'Ni-Vanuatu']);
        Country::insert(['name' => 'Vatican City', 'long_name' => 'State of the Vatican City', 'iso2' => 'VA', 'iso3' => 'VAT', 'numcode' => '336', 'calling_code' => '39', 'nationality' => 'of the Holy ']);
        Country::insert(['name' => 'Venezuela', 'long_name' => 'Bolivarian Republic of Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'numcode' => '862', 'calling_code' => '58', 'nationality' => 'Venezuelan']);
        Country::insert(['name' => 'Vietnam', 'long_name' => 'Socialist Republic of Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'numcode' => '704', 'calling_code' => '84', 'nationality' => 'Vietnamese']);
        Country::insert(['name' => 'Virgin Islands, British', 'long_name' => 'British Virgin Islands', 'iso2' => 'VG', 'iso3' => 'VGB', 'numcode' => '92', 'calling_code' => '1+284', 'nationality' => 'British Virg']);
        Country::insert(['name' => 'Virgin Islands, US', 'long_name' => 'Virgin Islands of the United States', 'iso2' => 'VI', 'iso3' => 'VIR', 'numcode' => '850', 'calling_code' => '1+340', 'nationality' => 'US Virgin Is']);
        Country::insert(['name' => 'Wallis and Futuna', 'long_name' => 'Wallis and Futuna', 'iso2' => 'WF', 'iso3' => 'WLF', 'numcode' => '876', 'calling_code' => '681', 'nationality' => 'Wallisian; F']);
        Country::insert(['name' => 'Western Sahara', 'long_name' => 'Western Sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'numcode' => '732', 'calling_code' => '212', 'nationality' => 'Sahrawian']);
        Country::insert(['name' => 'Yemen', 'long_name' => 'Republic of Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'numcode' => '887', 'calling_code' => '967', 'nationality' => 'Yemeni']);
        Country::insert(['name' => 'Zambia', 'long_name' => 'Republic of Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'numcode' => '894', 'calling_code' => '260', 'nationality' => 'Zambian']);
        Country::insert(['name' => 'Zimbabwe', 'long_name' => 'Republic of Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'numcode' => '716', 'calling_code' => '263', 'nationality' => 'Zimbabwean']);
    }

}
